"""Provenance Guard — Milestone 3
================================
Lightweight Flask boilerplate covering:
  1. App skeleton + env loading (GROQ_API_KEY)
  2. Signal 1 — LLM Holistic Analysis via Groq (llama-3.3-70b-versatile)
  3. SQLite structured audit log (init + insert helpers)
  4. POST /submit and GET /log endpoints

Scope is intentionally limited to Milestone 3. Stylometric heuristics,
word-frequency entropy, the ensemble engine, labels, and appeals are
deferred to later milestones.
"""

import os
import re
import sqlite3
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from groq import Groq

# Milestone 4 signal functions (Signal 2, Signal 3, ensemble engine).
from detection_signals import (
    calculate_combined_confidence,
    entropy_score,
    stylometric_score,
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
load_dotenv()  # loads GROQ_API_KEY (and friends) from .env

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_MODEL = "llama-3.3-70b-versatile"
DB_PATH = "audit_log.db"

# A single reusable Groq client. Instantiated lazily so the app can still
# boot (and serve /log) even if the key is missing during local dev.
_groq_client = None


def get_groq_client():
    """Return a cached Groq client, creating it on first use."""
    global _groq_client
    if _groq_client is None:
        if not GROQ_API_KEY:
            raise RuntimeError("GROQ_API_KEY is not set. Add it to your .env file.")
        _groq_client = Groq(api_key=GROQ_API_KEY)
    return _groq_client


app = Flask(__name__)

# ---------------------------------------------------------------------------
# Rate Limiter (FUTURE — Milestone 5 / production layer)
# ---------------------------------------------------------------------------
# Flask-Limiter is already pinned in requirements.txt. When we harden the
# submission flow we'll wrap the app here, e.g.:
#
#   from flask_limiter import Limiter
#   from flask_limiter.util import get_remote_address
#   limiter = Limiter(get_remote_address, app=app, default_limits=["100/hour"])
#
# and decorate POST /submit with @limiter.limit("10/minute").
# Left as a no-op placeholder for Milestone 3.


# ---------------------------------------------------------------------------
# Signal 1 — LLM Holistic Analysis
# ---------------------------------------------------------------------------
LLM_SYSTEM_PROMPT = (
    "You are a forensic text-provenance classifier. Assess the holistic "
    "semantic structure, predictability, and phrase transitions of the text "
    "the user provides and estimate the likelihood that it was generated by "
    "an AI language model.\n\n"
    "Respond with EXACTLY ONE number: a decimal float between 0.0 and 1.0, "
    "where 0.0 means highly likely human-written and 1.0 means highly likely "
    "AI-generated. Output ONLY the number. Do NOT include any words, labels, "
    "punctuation, explanation, units, or formatting. For example: 0.73"
)


def _coerce_float(raw: str) -> float:
    """Safely extract a 0.0–1.0 float from an LLM response string.

    The system prompt asks for a bare float, but we never trust that blindly.
    We pull the first number out of the response and clamp it to [0.0, 1.0]
    so a chatty or malformed reply can never break the JSON serializer.
    """
    match = re.search(r"[-+]?\d*\.?\d+", raw or "")
    if not match:
        return 0.0
    try:
        value = float(match.group())
    except (ValueError, TypeError):
        return 0.0
    return max(0.0, min(1.0, value))


def analyze_with_llm(text: str) -> float:
    """Signal 1: ask Groq's llama-3.3-70b-versatile for an AI-likelihood score.

    Returns a float in [0.0, 1.0]. Never raises on a malformed model reply —
    that case degrades to 0.0 via _coerce_float.
    """
    client = get_groq_client()
    completion = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": LLM_SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0.0,  # deterministic scoring
        max_tokens=10,    # we only need a short number back
    )
    raw = completion.choices[0].message.content.strip()
    return _coerce_float(raw)


# ---------------------------------------------------------------------------
# SQLite Audit Log
# ---------------------------------------------------------------------------
def get_db():
    """Open a fresh connection per request. Caller is responsible for close().

    sqlite3.Row gives us dict-like access for easy JSON serialization.
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    """Create the audit_log table if it doesn't already exist."""
    conn = get_db()
    try:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS audit_log (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp   TEXT    NOT NULL,
                content_id  TEXT    NOT NULL UNIQUE,
                creator_id  TEXT    NOT NULL,
                llm_score   REAL    NOT NULL,
                confidence  REAL    NOT NULL DEFAULT 0.0,
                attribution TEXT    NOT NULL DEFAULT 'pending',
                status      TEXT    NOT NULL DEFAULT 'classified',
                appeal_reasoning TEXT
            )
            """
        )
        conn.commit()
    finally:
        conn.close()


def migrate_add_appeal_reasoning():
    """Add the appeal_reasoning column to an existing table if it's missing.

    CREATE TABLE IF NOT EXISTS never alters an already-existing table, so a
    database created before Milestone 5 won't have this column. We inspect the
    live schema and ALTER only when needed. Idempotent — safe on every boot.
    """
    conn = get_db()
    try:
        cols = [row["name"] for row in conn.execute("PRAGMA table_info(audit_log)")]
        if "appeal_reasoning" not in cols:
            conn.execute("ALTER TABLE audit_log ADD COLUMN appeal_reasoning TEXT")
            conn.commit()
    finally:
        conn.close()


def insert_record(content_id, creator_id, llm_score,
                  confidence=0.0, attribution="pending", status="classified"):
    """Insert a single audit-log row and return the stored record as a dict."""
    timestamp = datetime.now(timezone.utc).isoformat()
    conn = get_db()
    try:
        conn.execute(
            """
            INSERT INTO audit_log
                (timestamp, content_id, creator_id, llm_score,
                 confidence, attribution, status)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (timestamp, content_id, creator_id, llm_score,
             confidence, attribution, status),
        )
        conn.commit()
    finally:
        conn.close()

    return {
        "timestamp": timestamp,
        "content_id": content_id,
        "creator_id": creator_id,
        "llm_score": llm_score,
        "confidence": confidence,
        "attribution": attribution,
        "status": status,
    }


def update_appeal_in_db(content_id, reasoning):
    """Flag a submission as appealed.

    Sets status -> 'under_review' and stores the creator's reasoning. Returns
    the updated row as a dict, or None if no row matches content_id.
    """
    conn = get_db()
    try:
        cur = conn.execute(
            """
            UPDATE audit_log
               SET status = 'under_review',
                   appeal_reasoning = ?
             WHERE content_id = ?
            """,
            (reasoning, content_id),
        )
        conn.commit()
        if cur.rowcount == 0:
            return None  # no matching content_id
        row = conn.execute(
            "SELECT * FROM audit_log WHERE content_id = ?", (content_id,)
        ).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def get_analytics_from_db():
    """Compute system-wide metrics from the audit log in a single pass.

    Division-by-zero safe: an empty table yields zeroes across the board
    rather than raising. Appeal rate counts rows that carry an
    appeal_reasoning, so an appeal stays counted even after a reviewer later
    moves the record to a resolved status.
    """
    conn = get_db()
    try:
        row = conn.execute(
            """
            SELECT
                COUNT(*)                                                     AS total,
                SUM(CASE WHEN appeal_reasoning IS NOT NULL THEN 1 ELSE 0 END) AS appeals,
                AVG(confidence)                                              AS avg_conf
            FROM audit_log
            """
        ).fetchone()
    finally:
        conn.close()

    total = row["total"] or 0
    appeals = row["appeals"] or 0

    if total == 0:
        # Empty database — nothing to average or divide by.
        return {
            "total_submissions": 0,
            "appeal_rate_percent": 0.0,
            "average_confidence": 0.0,
        }

    return {
        "total_submissions": total,
        "appeal_rate_percent": round((appeals / total) * 100, 2),
        "average_confidence": round(row["avg_conf"] or 0.0, 4),
    }


# ---------------------------------------------------------------------------
# Transparency Label Routing (Milestone 5)
# ---------------------------------------------------------------------------
def get_transparency_label(score: float) -> str:
    """Map a combined confidence score to its exact, verbatim label string.

    Thresholds (from planning.md):
        0.00 <= score < 0.35   -> Verified Human Work
        0.35 <= score <= 0.65  -> Uncertain Attribution
        0.65 <  score <= 1.00  -> AI-Generated Content
    """
    if score < 0.35:
        return ("Verified Human Work: Our system has high confidence that this "
                "content was entirely composed by a human creator.")
    elif score <= 0.65:
        return ("Uncertain Attribution: This content displays a mix of stylistic "
                "signals. Our system cannot definitively classify its origin. "
                "Originality remains unverified.")
    else:
        return ("AI-Generated Content: Our system detected strong structural and "
                "linguistic patterns characteristic of automated language models.")


# ---------------------------------------------------------------------------
# API Endpoints
# ---------------------------------------------------------------------------
@app.route("/", methods=["GET"])
def home():
    """Return a simple landing message for the root URL."""
    return jsonify({
        "message": "Provenance Guard API is running.",
        "endpoints": ["/submit", "/log", "/appeal", "/analytics"],
    }), 200


@app.route("/submit", methods=["POST"])
# @limiter.limit("10/minute")  # FUTURE: enable once the rate limiter is wired
def submit():
    """Accept {text, creator_id}, score via Signal 1, log, and return JSON."""
    data = request.get_json(silent=True) or {}
    text = data.get("text")
    creator_id = data.get("creator_id")

    if not text or not isinstance(text, str) or not text.strip():
        return jsonify({"error": "Field 'text' is required and must be a non-empty string."}), 400
    if not creator_id:
        return jsonify({"error": "Field 'creator_id' is required."}), 400

    content_id = str(uuid.uuid4())

    # --- Signal 1: LLM holistic analysis (Groq) ---------------------------
    try:
        llm_score = analyze_with_llm(text)
    except Exception as exc:  # network / API / config failure
        return jsonify({"error": f"LLM analysis failed: {exc}"}), 502

    # --- Signals 2 & 3: local heuristics (no network, never raise) --------
    stylometric = stylometric_score(text)
    entropy = entropy_score(text)

    # --- Ensemble: weighted combination + transparency label -------------
    confidence = calculate_combined_confidence(llm_score, stylometric, entropy)
    attribution = get_transparency_label(confidence)

    record = insert_record(
        content_id=content_id,
        creator_id=creator_id,
        llm_score=llm_score,
        confidence=confidence,
        attribution=attribution,
        status="classified",
    )

    # Surface the per-signal breakdown alongside the stored record so callers
    # can see how the confidence was composed.
    record["signal_scores"] = {
        "llm": llm_score,
        "stylometric": stylometric,
        "entropy": entropy,
    }

    return jsonify(record), 201


@app.route("/log", methods=["GET"])
def get_log():
    """Return the most recent audit-log entries as JSON.

    Optional ?limit=N query param (defaults to 20, capped at 100).
    """
    try:
        limit = int(request.args.get("limit", 20))
    except (TypeError, ValueError):
        limit = 20
    limit = max(1, min(limit, 100))

    conn = get_db()
    try:
        rows = conn.execute(
            "SELECT * FROM audit_log ORDER BY id DESC LIMIT ?",
            (limit,),
        ).fetchall()
    finally:
        conn.close()

    return jsonify([dict(row) for row in rows]), 200


@app.route("/appeal", methods=["POST"])
def appeal():
    """Accept {content_id, creator_reasoning} and flag the record for review."""
    data = request.get_json(silent=True) or {}
    content_id = data.get("content_id")
    creator_reasoning = data.get("creator_reasoning")

    if not content_id or not isinstance(content_id, str):
        return jsonify({"error": "Field 'content_id' is required and must be a string."}), 400
    if (not creator_reasoning or not isinstance(creator_reasoning, str)
            or not creator_reasoning.strip()):
        return jsonify({"error": "Field 'creator_reasoning' is required and must be a non-empty string."}), 400

    record = update_appeal_in_db(content_id, creator_reasoning.strip())
    if record is None:
        return jsonify({"error": f"No submission found for content_id '{content_id}'."}), 404

    return jsonify({
        "message": "Appeal received. Submission is now under review.",
        "content_id": content_id,
        "status": record["status"],
        "record": record,
    }), 200


@app.route("/analytics", methods=["GET"])
def analytics():
    """Return real-time system metrics (volume, appeal rate, avg confidence)."""
    return jsonify(get_analytics_from_db()), 200


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
with app.app_context():
    init_db()  # ensure the table exists securely within application context
    migrate_add_appeal_reasoning()  # patch pre-Milestone-5 databases safely

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=True)
