"""Provenance Guard — Milestone 3
================================
Lightweight Flask boilerplate covering:
  1. App skeleton + env loading (GROQ_API_KEY)
  2. Signal 1 — LLM Holistic Analysis via Groq (llama-3.3-70b-versatile)
  3. SQLite structured audit log (init + insert helpers)
  4. POST /submit and GET /log endpoints

Scope is intentionally limited to Milestone 3. Stylometric heuristics,
word-frequency entropy, the ensemble engine, labels, and appeals are
deferred to later milestones.
"""

import os
import re
import sqlite3
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from groq import Groq

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
load_dotenv()  # loads GROQ_API_KEY (and friends) from .env

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_MODEL = "llama-3.3-70b-versatile"
DB_PATH = "audit_log.db"

# A single reusable Groq client. Instantiated lazily so the app can still
# boot (and serve /log) even if the key is missing during local dev.
_groq_client = None


def get_groq_client():
    """Return a cached Groq client, creating it on first use."""
    global _groq_client
    if _groq_client is None:
        if not GROQ_API_KEY:
            raise RuntimeError("GROQ_API_KEY is not set. Add it to your .env file.")
        _groq_client = Groq(api_key=GROQ_API_KEY)
    return _groq_client


app = Flask(__name__)

# ---------------------------------------------------------------------------
# Rate Limiter (FUTURE — Milestone 5 / production layer)
# ---------------------------------------------------------------------------
# Flask-Limiter is already pinned in requirements.txt. When we harden the
# submission flow we'll wrap the app here, e.g.:
#
#   from flask_limiter import Limiter
#   from flask_limiter.util import get_remote_address
#   limiter = Limiter(get_remote_address, app=app, default_limits=["100/hour"])
#
# and decorate POST /submit with @limiter.limit("10/minute").
# Left as a no-op placeholder for Milestone 3.


# ---------------------------------------------------------------------------
# Signal 1 — LLM Holistic Analysis
# ---------------------------------------------------------------------------
LLM_SYSTEM_PROMPT = (
    "You are a forensic text-provenance classifier. Assess the holistic "
    "semantic structure, predictability, and phrase transitions of the text "
    "the user provides and estimate the likelihood that it was generated by "
    "an AI language model.\n\n"
    "Respond with EXACTLY ONE number: a decimal float between 0.0 and 1.0, "
    "where 0.0 means highly likely human-written and 1.0 means highly likely "
    "AI-generated. Output ONLY the number. Do NOT include any words, labels, "
    "punctuation, explanation, units, or formatting. For example: 0.73"
)


def _coerce_float(raw: str) -> float:
    """Safely extract a 0.0–1.0 float from an LLM response string.

    The system prompt asks for a bare float, but we never trust that blindly.
    We pull the first number out of the response and clamp it to [0.0, 1.0]
    so a chatty or malformed reply can never break the JSON serializer.
    """
    match = re.search(r"[-+]?\d*\.?\d+", raw or "")
    if not match:
        return 0.0
    try:
        value = float(match.group())
    except (ValueError, TypeError):
        return 0.0
    return max(0.0, min(1.0, value))


def analyze_with_llm(text: str) -> float:
    """Signal 1: ask Groq's llama-3.3-70b-versatile for an AI-likelihood score.

    Returns a float in [0.0, 1.0]. Never raises on a malformed model reply —
    that case degrades to 0.0 via _coerce_float.
    """
    client = get_groq_client()
    completion = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": LLM_SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0.0,  # deterministic scoring
        max_tokens=10,    # we only need a short number back
    )
    raw = completion.choices[0].message.content.strip()
    return _coerce_float(raw)


# ---------------------------------------------------------------------------
# SQLite Audit Log
# ---------------------------------------------------------------------------
def get_db():
    """Open a fresh connection per request. Caller is responsible for close().

    sqlite3.Row gives us dict-like access for easy JSON serialization.
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    """Create the audit_log table if it doesn't already exist."""
    conn = get_db()
    try:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS audit_log (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp   TEXT    NOT NULL,
                content_id  TEXT    NOT NULL UNIQUE,
                creator_id  TEXT    NOT NULL,
                llm_score   REAL    NOT NULL,
                confidence  REAL    NOT NULL DEFAULT 0.0,
                attribution TEXT    NOT NULL DEFAULT 'pending',
                status      TEXT    NOT NULL DEFAULT 'classified'
            )
            """
        )
        conn.commit()
    finally:
        conn.close()


def insert_record(content_id, creator_id, llm_score,
                  confidence=0.0, attribution="pending", status="classified"):
    """Insert a single audit-log row and return the stored record as a dict."""
    timestamp = datetime.now(timezone.utc).isoformat()
    conn = get_db()
    try:
        conn.execute(
            """
            INSERT INTO audit_log
                (timestamp, content_id, creator_id, llm_score,
                 confidence, attribution, status)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (timestamp, content_id, creator_id, llm_score,
             confidence, attribution, status),
        )
        conn.commit()
    finally:
        conn.close()

    return {
        "timestamp": timestamp,
        "content_id": content_id,
        "creator_id": creator_id,
        "llm_score": llm_score,
        "confidence": confidence,
        "attribution": attribution,
        "status": status,
    }


# ---------------------------------------------------------------------------
# API Endpoints
# ---------------------------------------------------------------------------
@app.route("/submit", methods=["POST"])
# @limiter.limit("10/minute")  # FUTURE: enable once the rate limiter is wired
def submit():
    """Accept {text, creator_id}, score via Signal 1, log, and return JSON."""
    data = request.get_json(silent=True) or {}
    text = data.get("text")
    creator_id = data.get("creator_id")

    if not text or not isinstance(text, str) or not text.strip():
        return jsonify({"error": "Field 'text' is required and must be a non-empty string."}), 400
    if not creator_id:
        return jsonify({"error": "Field 'creator_id' is required."}), 400

    content_id = str(uuid.uuid4())

    try:
        llm_score = analyze_with_llm(text)
    except Exception as exc:  # network / API / config failure
        return jsonify({"error": f"LLM analysis failed: {exc}"}), 502

    record = insert_record(
        content_id=content_id,
        creator_id=creator_id,
        llm_score=llm_score,
        confidence=0.0,         # placeholder until ensemble engine (M4)
        attribution="pending",  # placeholder until label logic (M5)
        status="classified",
    )

    return jsonify(record), 201


@app.route("/log", methods=["GET"])
def get_log():
    """Return the most recent audit-log entries as JSON.

    Optional ?limit=N query param (defaults to 20, capped at 100).
    """
    try:
        limit = int(request.args.get("limit", 20))
    except (TypeError, ValueError):
        limit = 20
    limit = max(1, min(limit, 100))

    conn = get_db()
    try:
        rows = conn.execute(
            "SELECT * FROM audit_log ORDER BY id DESC LIMIT ?",
            (limit,),
        ).fetchall()
    finally:
        conn.close()

    return jsonify([dict(row) for row in rows]), 200


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
init_db()  # ensure the table exists at import time (covers `flask run` too)

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=True)
